USE Quan_li_thu_cung
GO

CREATE TABLE ANIMALS
(
ID VARCHAR(15),
NAME VARCHAR(50),
HEIGHT FLOAT,
WEIGHT FLOAT,
COLOR VARCHAR(50)

);
GO

INSERT INTO ANIMALS VALUES('DOG1','HUSKY',100,50,'BLACK')
INSERT INTO ANIMALS VALUES('CAT1','MEO 34',50,10,'WHITE')
INSERT INTO ANIMALS VALUES('PIG1','BIG PIG',150,50,'PINK')
INSERT INTO ANIMALS VALUES('CHICKEN1','RI CHICKEN',50,5,'YELLOW')
INSERT INTO ANIMALS VALUES('DOG2','PITPULL',70,40,'ORANGE')
